$(document).ready(function(){
    $(".menu").click(function(){
        $(this).toggleClass("active")
        $(".lista").toggleClass("active")
    })
});
$(document).ready(function(){
    $(".lista").click(function(){
        $(this).toggleClass("active")
        $(".menu").toggleClass("active")
    })
});